#ifndef SIMPLEFTPONTCP_RESPONSE_H
#define SIMPLEFTPONTCP_RESPONSE_H

enum Response : unsigned char {
    OK = 0,
    ERROR = 1,
    NOT_DIRECTORY = 2,
    NOT_REGULAR_FILE = 3,
    NOT_EXISTS = 4,
    ALREADY_EXISTS = 5
};

#endif //SIMPLEFTPONTCP_RESPONSE_H
